// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1fd67601-d603-424b-880d-59b739e0e245",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_weOJfm2lT",
    "aws_user_pools_web_client_id": "7rrug48sgcmvo21bjrh4c6n65n"
};


export default awsmobile;
